[package]
name = "day_6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
read_char = "0.1.1"
circular-queue = "0.2.6"
#queues = "1.1.0"
itertools = "0.10.5"